import { Metadata } from "next"

async function getData() {
    const response = await fetch('https://jsonplaceholder.typicode.com/posts',{
        next: {
            revalidate: 60
        }
    });
    return response.json();
}

export const metadata: Metadata = {
    title: 'Chart | Next App',
    description: 'Generated by create next app',
  }

export default async function Posts(){
    const posts = await getData();

    return (
        <ul>
            {posts.map((post: any) => (
                <li key={post.id}>{post.title}</li>
            ))}
        </ul>
    )
}